### ISSUE TITLE
Ctrl-M keybinding conflicts with matching bracket on windows and linux

### ISSUE THREAD

**Issue by forivall** [smashwilson/merge-conflicts#157]
I would be in favor of changing this keybinding for linux and windows. Alt-m appears free, tested using the keybinding resolver (alt-.).

**Comment by aurelienbottazini** [comment]
Ctrl-M is also in conflict on mac.

**Comment by smashwilson** [comment]
Oh, so it does! Using Alt-M chords instead sounds reasonable to me. :+1: I'll change them in the next release; if you don't want to wait that long, you can add the following to your keymap:

```coffeescript
'atom-text-editor.conflicted':
  'alt-m down': 'merge-conflicts:next-unresolved'
  'alt-m up': 'merge-conflicts:previous-unresolved'
  'alt-m enter': 'merge-conflicts:accept-current'
  'alt-m r': 'merge-conflicts:revert-current'
  'alt-m 1': 'merge-conflicts:accept-ours'
  'alt-m 2': 'merge-conflicts:accept-theirs'

'atom-workspace':
  'alt-m d': 'merge-conflicts:detect'
```

@aurelienbottazini: Are the alt-m chords open on Mac as well? I could also make the cmd-m for Mac, instead. (I could also check myself when I'm on my Mac again.)

I am a *little* nervous about yanking the keybindings around and messing with everyone's muscle memory like this, but since we've been breaking bracket-matcher I think that's a cost we'll have to pay.

Honestly, I've become reluctant to specify keybindings within a package at all, because I can't predict what other packages a user will have active and conflicts seem inevitable for *someone*. When I made my other package, I made it a ["bring your own keybinding"]((https://github.com/smashwilson/stacktrace#commands)) one instead. It's a little less nice to set up as a beginner (you need to read the README and edit your keymap and so on) but it saves us trying to hunt for chords that aren't taken by other core or popular packages.

**Comment by aurelienbottazini** [comment]
@smashwilson Yes alt-m is open on mac.
Cmd-m on mac is binded to _application minimize_.

**Comment by forivall** [comment]
Hopefully, either the atom team or someone in the community works out a solution to this keybinding problem once and for all; conflict resolution, a simple ui to rebind them, etc. (\*\*cough\*\* avoiding the bugs that kde's keybinding resolution has \*\*cough\*\*)
