### ISSUE TITLE
Weird display bugs

### ISSUE THREAD

**Issue by habermann24** [smashwilson/merge-conflicts#79]
I'm experiencing strange issues when using the merge tool.
It happens when there are multiple conflicts in the same file and i chose to pick something in the middle.

It's hard to explain, but here is a gif:

![untitled](https://cloud.githubusercontent.com/assets/7480/4726407/468e0a70-5962-11e4-8adf-b61e08994da7.gif)

A similar issue occurs when i accidentally edit a part of the file which is not part of the conflicts.
It ends up destroying the merge-conflicts functionality and i have to start all over again.
The annoying part is that even undos won't bring me to the state before everything screws up. 

My ATOM Package list:
(Atom version: 0.138.0)

packages (8)
├── clipboard-history@0.6.1
├── color-picker@1.2.5
├── git-history@1.1.2
├── linter@0.7.3
├── linter-coffeelint@0.1.7
├── linter-rubocop@0.2.1
├── linter-scss-lint@0.0.11
└── merge-conflicts@1.2.7

**Comment by smashwilson** [comment]
Overlay decorations are live :tada: They'll be included in the next release. The right-hand side of the control bars can be a little off because the vertical scrollbar width doesn't seem to be accurate. It'll do, though.

I'm now doing much less evil DOM hackery myself, and using a more stable API. I'm hopeful that it should hammer our CPUs less, too.

**Comment by burabure** [comment]
Nice!!

**Comment by habermann24** [comment]
Sweeeeeet!! Thank you so much!
